// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "books-api/internal/entity"
	exception "books-api/pkg/exception"
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "books-api/internal/model"

	service "books-api/internal/services"
)

// AuthorService is an autogenerated mock type for the AuthorService type
type AuthorService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *AuthorService) Create(ctx context.Context, _a1 *entity.UpsertAuthor) *exception.Exception {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UpsertAuthor) *exception.Exception); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exception.Exception)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AuthorService) Delete(ctx context.Context, id string) *exception.Exception {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, string) *exception.Exception); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exception.Exception)
		}
	}

	return r0
}

// FindOne provides a mock function with given fields: ctx, id
func (_m *AuthorService) FindOne(ctx context.Context, id string) (*entity.Author, *exception.Exception) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *entity.Author
	var r1 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Author, *exception.Exception)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Author); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *exception.Exception); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exception.Exception)
		}
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *AuthorService) List(ctx context.Context, req model.ListReq) (*service.ListAuthorResp, *exception.Exception) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *service.ListAuthorResp
	var r1 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, model.ListReq) (*service.ListAuthorResp, *exception.Exception)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListReq) *service.ListAuthorResp); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ListAuthorResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListReq) *exception.Exception); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exception.Exception)
		}
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *AuthorService) Update(ctx context.Context, id string, _a2 *entity.UpsertAuthor) *exception.Exception {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, string, *entity.UpsertAuthor) *exception.Exception); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exception.Exception)
		}
	}

	return r0
}

// NewAuthorService creates a new instance of AuthorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorService {
	mock := &AuthorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
