// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// ConsumerKafkaHandler is an autogenerated mock type for the ConsumerKafkaHandler type
type ConsumerKafkaHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, message
func (_m *ConsumerKafkaHandler) Execute(ctx context.Context, message *kafka.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerKafkaHandler creates a new instance of ConsumerKafkaHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerKafkaHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerKafkaHandler {
	mock := &ConsumerKafkaHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
