// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "books-api/internal/entity"
	exception "books-api/pkg/exception"
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "books-api/internal/services"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, model
func (_m *UserService) Login(ctx context.Context, model *entity.UserLogin) (*service.UserLoginResponse, *exception.Exception) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *service.UserLoginResponse
	var r1 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserLogin) (*service.UserLoginResponse, *exception.Exception)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserLogin) *service.UserLoginResponse); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserLogin) *exception.Exception); ok {
		r1 = rf(ctx, model)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*exception.Exception)
		}
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, model
func (_m *UserService) Register(ctx context.Context, model *entity.UserLogin) *exception.Exception {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *exception.Exception
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserLogin) *exception.Exception); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exception.Exception)
		}
	}

	return r0
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
