version: '3.8'

services:
  books-api-web:
    build: .
    command: ["./books-api-web"]
    ports:
      - "9004:9004"
    environment:
      APP_NAME: "books-api"
      APP_ENV: "development"
      GIN_MODE: "release"
      APP_DEBUG: "true"
      APP_VERSION: "v1"
      HTTP_PORT: "9004"
      JWT_SECRET_ACCESS_TOKEN: "wkhB8NarrReKujasQzlRaOQGOO4S1G884ol9SIyQ7Fr4zxLBJI9Ezml4DeaisAss"
      HMAC_SECRET_ACCESS_TOKEN: "HmacSHA512"
      DB_CONNECTION: "sqlite"
      DB_PREFIX: "goodreads_"
      ALLOW_ORIGINS: "*"
      ALLOW_METHODS: "POST,GET,PUT,DELETE,OPTIONS"
      ALLOW_HEADERS: "*"
      LOG_PATH: "./logs/"
    restart: on-failure
